name: Run sanity checks

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: "Check package integrity"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam build
        name: Check build success
      - run: gleam format --check src test
        name: Check format validity
